### PR TITLE
Fix #35

### LINKED ISSUE #35: `Gsk::RoundedRect#init` corrupts memory
The following code (just example code to create Gsk::RoundedRect):
```crystal
require "gtk4"

loop do
  w = 100
  h = 100

  bounds = Graphene::Rect.new
  bounds.init(0.0f32, 0.0f32, w.to_f32, h.to_f32)

  corner = Graphene::Size.new
  corner.init(12.0f32, 12.0f32)

  rounded_rect = Gsk::RoundedRect.new
  rounded_rect.init(bounds, corner, corner, corner, corner)
end
```

Results in memory issues, depending on whether the GC is used or not.

If BDWGC is used:
```
[blobcodes@toolbox mangaba]$ crystal run src/test2.cr
Invalid memory access (signal 11) at address 0x0
[0x481b76] *Exception::CallStack::print_backtrace:Nil +118 in /var/home/blobcodes/.cache/crystal/crystal-run-test2.tmp
[0x470f7a] ~procProc(Int32, Pointer(LibC::SiginfoT), Pointer(Void), Nil) +330 in /var/home/blobcodes/.cache/crystal/crystal-run-test2.tmp
[0x7f3623488ac0] ?? +139870496918208 in /lib64/libc.so.6
Invalid memory access (signal 7) at address 0x0
[0x481b76] *Exception::CallStack::print_backtrace:Nil +118 in /var/home/blobcodes/.cache/crystal/crystal-run-test2.tmp
[0x470f7a] ~procProc(Int32, Pointer(LibC::SiginfoT), Pointer(Void), Nil) +330 in /var/home/blobcodes/.cache/crystal/crystal-run-test2.tmp
[0x7f3623488ac0] ?? +139870496918208 in /lib64/libc.so.6
Program received and didn't handle signal BUS (7)
```

..and if no GC is used:
```
⬢[blobcodes@toolbox mangaba]$ crystal run src/test2.cr -Dgc_none
malloc(): corrupted top size
Program received and didn't handle signal IOT (6)
```

While using this inside a vfunc, I also received this error:
```
corrupted size vs. prev_size
Program received and didn't handle signal IOT (6)
```

I tested on both release v0.11 and master, the behaviour doesn't change.

I think this may have something to do with RoundedRect having a fixed-size array in its struct:
```crystal
  struct RoundedRect # 48 bytes long
    bounds : LibGraphene::Rect
    corner : Void[4]
  end
```

However: `puts sizeof(Void[4]) # => 4`

I think this must be `Void*[4]` instead. Maybe this happened because not enough space has been allocated.

EDIT: the correct awnser would have been `LibGraphene::Size[4]`

### PR DESCRIPTION
**Pull request by BlobCodes**
Closes #35 

The issue was hard to find, but very easy to understand.
The parameter `include_namespace` was passed to `to_lib_type`, but not as a named parameter (and thus `structs_as_void` was set to `include_namespace` - which is by default `true`).

### CODE REVIEW

**Comment by BlobCodes** [comment]
It seems like other parts of gi-crystal have been influenced by that bug.. (test fail)

**Comment by hugopl** [comment]
Nice catch, I need to revisit the code under `generator/helper.cr`, it grew a lot and the many overloads are confusing sometimes. 

I'll try to add a test for the issue and merge this patch this week, thanks very much!

**Comment by hugopl** [comment]
I'm trying to add a test to mimic issue #35 , but the interesting part is that this PR seems to not change any code ran by the code snippet in the issue, or I'm misreading something (as usual).

Trying to write a test for this just uncover the fact that only the simpler use cases for structs are working.

```diff
diff --git a/spec/libtest/test_subject.h b/spec/libtest/test_subject.h
index 84e8c92..d0f56a2 100644
--- a/spec/libtest/test_subject.h
+++ b/spec/libtest/test_subject.h
@@ -33,6 +33,16 @@ typedef struct _TestPoint {
   int y;
 } TestPoint;
 
+/**
+ * TestTwoPoints:
+ * @points:
+ *
+ * Used to test static array on structs.
+ */
+typedef struct _TestTwoPoints {
+  TestPoint points[2];
+} TestTwoPoints;
+
 /**
  * TestStruct:
  * @in: A attribute using a invalid Crystal keyword.
diff --git a/spec/struct_spec.cr b/spec/struct_spec.cr
index a6a9a3c..6506858 100644
--- a/spec/struct_spec.cr
+++ b/spec/struct_spec.cr
@@ -21,6 +21,12 @@ describe "Struct bindings" do
     truct.point.y.should eq(2)
   end
 
+  it "can have static array of structs as attributes" do
+    twopoints = Test::TwoPoints.new
+    twopoints.points = {Test::Point.new(1, 2), Test::Point.new(2, 3)}
+    twopoints.points.should eq({Test::Point.new(1, 2), Test::Point.new(2, 3)})
+  end
+
   it "can have nullable string attributes" do
     truct = Test::Struct.new(string: "hey")
     truct.string.should eq("hey")
```

**Comment by hugopl** [comment]
I got into this same issue now trying to fix the harfbuzz problem...

**Comment by hugopl** [comment]
I rebased this, solved the conflicts and merged into 023347f5f87438a6f89e8d8b4f1680bf063eec94 on your behalf.

**Pull request closed without merging**
