### PR TITLE
GC resistant subclasses

### PR DESCRIPTION
**Pull request by BlobCodes**
Extracted from #14 
Requires #26 

This (incomplete) PR allows having pointers to crystal objects in your gobject subclass. This is achieved by splitting the subclass into a pointer class and a data class (which does the actual work).

As previously the `implementation do ... end` macro has been criticised, it has now been removed.
With this (and the current state of #26), the syntax for defining a subclass is as follows:

```crystal
class TestPaintable < GObject::Object
  include Gdk::Paintable

  @[GObject::PrivateDataClass]
  class TestPrivate < self
    @test = "hi"

    def do_snapshot(snapshot, width, height)
      puts "Snapshot: #{width}x#{height}, snapshot: #{snapshot}, test: #{@test}, self: #{self}"
    end
  end
end
```

There only needs to be one class inheriting from the pointer class, having the annotation `PrivateDataClass`.

### CODE REVIEW

**Comment by hugopl** [comment]
I was thinking about the problem of garbage collected objects with Crystal vfuncs and alive in C and had a idea, what if:

```
obj = MyTakeAwayObj.new
some_api.add_obj(obj)
obj.keep_alive!
```

This `GObject::Object#keep_alive!` would:
- Add the object to the closure manager, so it wont get GC'ed.
- Store a `GWeakRef` for the object in ClosureManager.
- The callback, called at object disposal, would just remove the pointer from the `ClosureManager`, letting the object be GCed.

# Pros
Pretty simple, minimal overhead

# Cons
The solution isn't fully transparent to the user, but the exceptions throw can teach it.

**Comment by BlobCodes** [comment]
> I was thinking about the problem of garbage collected objects with Crystal vfuncs and alive in C and had a idea, what if:
> 
> ```
> obj = MyTakeAwayObj.new
> some_api.add_obj(obj)
> obj.keep_alive!
> ```
> 
> This `GObject::Object#keep_alive!` would:
> 
>     * Add the object to the closure manager, so it wont get GC'ed.
> 
>     * Store a `GWeakRef` for the object in ClosureManager.
> 
>     * The callback, called at object disposal, would just remove the pointer from the `ClosureManager`, letting the object be GCed.
> 
> 
> # Pros
> 
> Pretty simple, minimal overhead
> # Cons
> 
> The solution isn't fully transparent to the user, but the exceptions throw can teach it.

I had also experimented with weakrefs but couldn't get it working. It's neither a good, nor a bad solution but at least it's better than the current state.

Maybe it's worth looking at implementations of GObject in other garbage-collected languages.

**Comment by hugopl** [comment]
> Maybe it's worth looking at implementations of GObject in other garbage-collected languages.

Yes, always is. However IMO this isn't a high priority, since there's a bunch of important stuff missing yet.

**Comment by BlobCodes** [comment]
> I was thinking about the problem of garbage collected objects with Crystal vfuncs and alive in C and had a idea, what if:
> 
> ```
> obj = MyTakeAwayObj.new
> some_api.add_obj(obj)
> obj.keep_alive!
> ```
> 
> This `GObject::Object#keep_alive!` would:
> 
>     * Add the object to the closure manager, so it wont get GC'ed.
> 
>     * Store a `GWeakRef` for the object in ClosureManager.
> 
>     * The callback, called at object disposal, would just remove the pointer from the `ClosureManager`, letting the object be GCed.
> 
> 
> # Pros
> 
> Pretty simple, minimal overhead
> # Cons
> 
> The solution isn't fully transparent to the user, but the exceptions throw can teach it.

I just thought about this a little more and I think:
1. this is a very suboptimal solution
2. It's probably not even possible
3. It's not "minimal overhead"

Why it is suboptimal:
If we need to have a `keep_alive!` call inside crystal, we cannot instantiate these subclasses from outside crystal.
One important use-case which requires this is instantiating widgets in .ui files, which I want to make use of to have cleaner code.

Why it probably won't work:
This is a perfect example of a retain cycle.
As long as the GObject ref_count is `> 0`, a reference to the object is set inside crystal.
This reference itself will keep the object alive, but the object itself is the thing increasing the reference count.

Why it has significant overhead:
If we remove references to our object from the c world, the pointer would be removed from the ClosureManager. This means that we need to redo the `keep_alive!` call, which could be complicated in some situations.

---

I think we must split the implementation into two objects - one "dumb" pointer class (just like all other GObject classes generated by gi-crystal) and one class storing the data.
I'm not sure if we can hide the second class somehow, but I don't think this is possible.

**Comment by hugopl** [comment]
Yes, the use case of letting the Gtk::Builder instantiate the GObject is the most important one.

Maybe it's possible if we let the `instance_init` instantiate the Crystal object when the object is created in C world, maybe passing the Crystal instance on `user_data` pointer... then if the user_data pointer is nil, the `instance_init` creates the Crystal instance... taking care to avoid double init and infinite loops and probably needing to add the GWeakRef to ClosureManager.

But I think there are still a lot of other important things missing in the bindings, so despite of this being a very important topic, it isn't in the priority list yet, since there's workarounds possible, not always beautiful ones, but possible.

My main concern is: The end solution must still look like ordinary Crystal code and don't have undefined behavior if the user do this or that.

**Pull request closed without merging**
